set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 10 
set -g mouse on
set -g base-index 1
set-option -g renumber-windows on 

set -g status-style bg=#0B0E14,fg=#BFBDB6
set -g status-left ""
# set -g status-left-length 50
set -g status-right-length 100
set -g status-right "#[bg=#0B0E14,fg=#39BAE6]▏ [#(basename #{pane_current_path})] #(~/local/bin/task_polybar.sh)"

set -g window-status-format "#[bg=#0B0E14,fg=#565B66]  #I: #W  "
set -g window-status-current-format "#[bg=#FF8F40,fg=#0B0E14,bold]  #I: #W  "
set -g window-status-style bg=#0B0E14,fg=#565B66
set -g window-status-current-style bg=#FF8F40,fg=#0B0E14,bold
set -g window-status-activity-style bg=#0B0E14,fg=#FF8F40
set -g window-status-separator ''

set -g pane-border-style bg=default,fg=#565B66
set -g pane-active-border-style bg=default,fg=#39BAE6

set -g message-style bg=#0B0E14,fg=#E6B450,bold
set -g message-command-style bg=#0B0E14,fg=#E6B450,bold

set -g mode-style bg=#1B3A5B,fg=#BFBDB6

unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."

bind ^ last-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe "wl-copy"
bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

bind C new-window -c '#{pane_current_path}'

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v  -c "#{pane_current_path}"

bind-key -r < swap-window -t -1 \; select-window -t -1
bind-key -r > swap-window -t +1 \; select-window -t +1

set -g clock-mode-colour "#39BAE6"
